mv text/*.aux garbage
mv text/*.bbl garbage
mv text/*.bcf garbage
mv text/*.blg garbage
mv text/*.fdb_latexmk garbage
mv text/*.fls garbage
mv text/*.log garbage
mv text/*.out garbage
mv text/*.run.xml garbage
mv text/*.synctex.gz garbage
